# Base everything on NVIDIA’s NVMe devkit machine
require conf/machine/jetson-orin-nano-devkit-nvme.conf

# Let overrides written for the base also apply to this machine,
# while still allowing a more specific override for *this* machine.
# Order: least-specific ... most-specific
MACHINEOVERRIDES =. "jetson-orin-nano-devkit-nvme:"

# Swupdate definitions
USE_REDUNDANT_FLASH_LAYOUT = "1"
# PARTITION_LAYOUT_EXTERNAL_DEFAULT = "flash_l4t_t234_nvme_data.xml"
# PARTITION_LAYOUT_EXTERNAL_REDUNDANT = "flash_l4t_t234_nvme_rootfs_ab_data.xml"

UBOOT_EXTLINUX = "1"

# The default in meta-tegra assumes ~64GB external media. With a 500GB NVMe,
# bump the "virtual device size" so the flash layout has room for larger UDA.
TEGRA_EXTERNAL_DEVICE_SECTORS ?= "250000000"

RC_CAR_DATA_PARTLABEL ?= "UDA"
RC_CAR_DATA_PART_FSTYPE ?= "ext4"
# 32 GiB, 4K-aligned
RC_CAR_DATA_PART_SIZE_BYTES ?= "34359738368"
RC_CAR_DATA_AUTO_RESIZE ?= "1"

PREFERRED_PROVIDER_virtual/dtb = "rc-car-devicetree"
KERNEL_DEVICETREE:rc-car-machine = "rc-car-device-tree-oe4t.dtb"

UBOOT_EXTLINUX_FDT = "rc-car-device-tree-oe4t.dtb"
UBOOT_EXTLINUX_FDTOVERLAYS = "tegra234-p3767-camera-p3768-imx219-dual.dtbo rc-car-overlay.dtbo"

TEGRA_PLUGIN_MANAGER_OVERLAYS:append = " tegra234-p3767-0000+p3509-a02-hdr40.dtbo"
    
